name: Unit test (powered by themis.vim) runner

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      vim_type:
        required: true
        type: string
      vim_version:
        required: true
        type: string
      download:
        required: false
        type: string

jobs:
  run-themis-tests:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Vim
        id: vim
        uses: thinca/action-setup-vim@40587a4deeeaf61ef8086bd3badd42e734a67093 # v3.0.2
        with:
          vim_type: ${{ inputs.vim_type }}
          vim_version: ${{ inputs.vim_version }}
          download: ${{ inputs.download }}
      - name: Show Vim version
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: Setup themis.vim
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: thinca/vim-themis
          path: themis
      - name: Run test
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./themis/bin/themis --reporter tap
